version: '3.8'

services:
  fastapi_server:
    container_name: ${PROJECT_NAME}_fastapi_server
    build: ./backend
    restart: always
    command: "sh -c 'uvicorn app.main:app --reload --workers 3 --host 0.0.0.0 --port 8000'"
    volumes:
      - ./backend/app:/code
    expose:
      - 8000    
    env_file: ".env"

  caddy_reverse_proxy:
    container_name: ${PROJECT_NAME}_caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - EXT_ENDPOINT1=${EXT_ENDPOINT1}
      - LOCAL_1=${LOCAL_1}
      - LOCAL_2=${LOCAL_2}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

